### ISSUE TITLE
HuggingFace locked to 30p output

### ISSUE THREAD

**Issue by DDBE12** [KwaiVGI/LivePortrait#128]
Hey, this is an awesomely easy-to-use tool, especially the HuggingFace, for people who can't deal with command-line prompts. However, I've found no matter what framerate my driving video has, the output is locked to 30p, which is unfortunate if your project is 24p or 25p.

Please consider updating the HuggingFace to use the original framerate of the driving video.

**Comment by Inferencer** [comment]
can i also add to this, not to hijack but while we are on the subject of HF because I haven't used local in a while so not sure if this has been fixed on local
but the re-targeting of an image that was 1080x1080 to lip closed at 0 on the slider and eye openness changed to 0.22 the output image was 1072x1072 can we ensure it is the same size as the original as I use it to edit the first frame of my driving vid to include a closed mouth and the size change messed things up

**Comment by cleardusk** [comment]
Thanks for your feedbacks @DDBE12 @Inferencer. We will check it later.

**Comment by cleardusk** [comment]
It seems to be fixed now: https://huggingface.co/spaces/KwaiVGI/LivePortrait @DDBE12 @Inferencer

**Comment by DDBE12** [comment]
On the HuggingFace, not just on the repo? Thank you so much!

**Comment by cleardusk** [comment]
The repo is fixed already.
