### ISSUE TITLE
Cropping Feeback?

### ISSUE THREAD

**Issue by samsonsite1** [KwaiVGI/LivePortrait#187]
I don't fully understand cropping parameters or what's being cropped from the source image or driving video.

Is there some way to get visual feedback on what's being cropped?
Thanks.

**Comment by zzzweakman** [comment]
> I don't fully understand cropping parameters or what's being cropped from the source image or driving video.
> 
> Is there some way to get visual feedback on what's being cropped? Thanks.

Thank you for your attention. If you upload a source image without cropping and the face region in the image is too small, you might get a terrible output result. 

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/c01fa261-8016-4f64-9ced-407d92e0d17f">

This is because our model was trained with faces that are aligned and cropped. For optimal results during inference, it's best to upload an image where the face occupies a significant portion of the frame. Cropping helps process images that don't meet this requirement.

The same logic applies to videos. If the facial area is too small, it will seriously affect the generation effect
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/ec1f0288-948f-4f0b-ba96-b2792ba12882">
In our [code](https://github.com/KwaiVGI/LivePortrait/blob/main/src/gradio_pipeline.py#L66), we automatically crop videos that aren't square to achieve the best results.

If you have any further questions, feel free to ask! @samsonsite1

**Comment by FurkanGozukara** [comment]
@zzzweakman excellent explanation ty so much

do you have plans to add face index feature? like if a video has 2 faces we can set to animate index 1 or like 0 or all

**Comment by zzzweakman** [comment]
> @zzzweakman excellent explanation ty so much
> 
> do you have plans to add face index feature? like if a video has 2 faces we can set to animate index 1 or like 0 or all

Regarding the face index feature, it would indeed be an interesting addition. However, we are concerned that introducing it might complicate the Gradio interaction logic, potentially increasing the learning curve for new users. 

We believe that one of the key missions of this repository is to disseminate and make it accessible to a wide range of interested users, regardless of the barrier to entry. Therefore, I think those who are interested in additional features will find them in the LivePortrait community resources—if they are willing to spend more time exploring. 

We also particularly appreciate the contributions you have made to the dissemination of this project : ) @FurkanGozukara
