### ISSUE TITLE
Would you let me know where can I find train code?

### ISSUE THREAD

**Issue by hehe717** [KwaiVGI/LivePortrait#246]
Hello,

I am so interested in this repository, and I wanna train Liveportrait myself.
Would you please let me know where can i find train code?

**Comment by zzzweakman** [comment]
> Hello,
> 
> I am so interested in this repository, and I wanna train Liveportrait myself. Would you please let me know where can i find train code?

Thank you for your interest in this repository. Unfortunately, due to certain constraints, we are unable to provide the training code at this time. However, you can refer to the training code provided in the [Open Facevid2vid](https://github.com/zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis) project as an alternative.
