### ISSUE TITLE
8.20号代码更新后，输入图片张嘴，视频驱动之后，生成的视频嘴闭不上了

### ISSUE THREAD

**Issue by huipengo** [KwaiVGI/LivePortrait#341]
刚拉了8.20号更新的代码，发现输入图片如果是张嘴的，视频驱动之后，生成的视频的嘴闭不上了。
8.17号的代码是没问题的

**Comment by cleardusk** [comment]
感谢反馈。@huipengo 可否提供测试用例呢？

Thanks for your feedback, could you please provide the tested cases?

**Comment by Mystery099** [comment]
Thanks for your feedback. @huipengo 

This is because we changed the default value of `flag_normalize_lip` from True to False in `src/config/argument_config.py`. If you want to automatically close the mouth before starting the animation when the mouth is open in the source image, you can use the following:
```bash
python inference.py --flag_normalize_lip
```

**Comment by huipengo** [comment]
> Thanks for your feedback. @huipengo
> 
> This is because we changed the default value of `flag_normalize_lip` from True to False in `src/config/argument_config.py`. If you want to automatically close the mouth before starting the animation when the mouth is open in the source image, you can use the following:
> 
> ```shell
> python inference.py --flag_normalize_lip
> ```

可以了，感谢
