### ISSUE TITLE
ImportError: cannot import name 'mesh_core_cython'

### ISSUE THREAD

**Issue by caslix** [KwaiVGI/LivePortrait#8]
Hello! The installation went well, but an error is displayed at startup:

ImportError: cannot import name 'mesh_core_cython' from 'src.utils.dependencies.insightface.thirdparty.face3d.mesh.cython' (unknown location)

**Comment by shangshangdyx** [comment]
1. conda activate LivePortrait
2. pip install cython
3. cd src/utils/dependencies/insightface/thirdparty/face3d/mesh/cython
4. python setup.py build_ext --inplace
enjoy it！

**Comment by caslix** [comment]
Thank you very much! Everything is working now. Gorgeous implementation!

**Comment by cleardusk** [comment]
Thanks for your feedback. The repo does not rely on a 3D rendering module; we will refine it in the future. 
Meanwhile, you can use this temporary solution. @shangshangdyx Or, use python3.9 may work well.

**Comment by shomc-xxj** [comment]
(cleanenv) D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\cython>python setup.py build_ext -i
Compiling mesh_core_cython.pyx because it changed.
[1/1] Cythonizing mesh_core_cython.pyx
D:\ComfyUI_windows_portable\python_embeded\cleanenv\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
mesh_core.cpp
(cleanenv) D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\cython>python -c "from insightface.thirdparty.face3d.mesh.cython import mesh_core_cython; print('mesh_core_cython imported successfully')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'mesh_core_cython' from 'insightface.thirdparty.face3d.mesh.cython' (unknown location)
