### ISSUE TITLE
可以用于音视频融合时的唇声同步任务吗？

### ISSUE THREAD

**Issue by KDD2018** [KwaiVGI/LivePortrait#95]

**Comment by holasyb** [comment]
cy 想知道怎么用

**Comment by zzzweakman** [comment]
We have discovered that the implicit-keypoint-based framework can be extended to audio-driven control. The experimental results are detailed in Appendix C of our paper. Due to internal limitations, we are sorry that we are unable to provide this model now. However, you can follow the instructions in Appendix C to train an audio-driven model on your own :) @KDD2018 @holasyb

**Comment by markson14** [comment]
> We have discovered that the implicit-keypoint-based framework can be extended to audio-driven control. The experimental results are detailed in Appendix C of our paper. Due to internal limitations, we are sorry that we are unable to provide this model now. However, you can follow the instructions in Appendix C to train an audio-driven model on your own :) @KDD2018 @holasyb

Hi, great work! I really appreciate it. I have one question about audio-driven according to your Appendix C.

When I use audio-driven method, I am not able to use retargeting module since it capture the keypoints from videos. Am I correct?

**Comment by TengliEd** [comment]
@zzzweakman I am quite curious about what level the audio-driven model can achieve. Could you please provide us with some results you've produced? Since then, we can check if we implement correctly following your method.
